package org.bgee.controller.exception;

/**
 * This {@code Exception} is thrown when more than one value is provided
 * to a {@link org.bgee.controller.URLParameters.Parameter} that does not allow multiple values.
 * <p>
 * It extends a {@code RuntimeException} for convenience, as any such errors should be 
 * catch by the {@code FrontController} anyway.
 * 
 * @author  Mathieu Seppey
 * @author Frederic Bastian
 * @version Bgee 13, Dec 2014
 * @see     org.bgee.controller.RequestParameters
 * @since   Bgee 13
 */
public class MultipleValuesNotAllowedException extends RuntimeException
{

    private static final long serialVersionUID = -7861781334770127365L;

    /**
     * Default constructor
     */
    public MultipleValuesNotAllowedException()
    {
        super();
    }

    /**
     * Constructor with an additional {@code message} argument. 
     * This message MUST be really basic and understandable, 
     * as it will be displayed to the user. 
     * 
     * The full error message will be generated by the {@code FrontController}. 
     * Only the {@code FrontController} should set a real error message 
     * for this exception.
     * 
     * @param message   a {@code String} giving details about the exception, 
     *                  BUT despite usually, it MUST be really basic and 
     *                  understandable, as it will be displayed to the user. 
     */
    public MultipleValuesNotAllowedException(String message)
    {        
        super("You tried to set several values for the parameter "
                + message + " that does not accept multiple values.");
    }

    /**
     * Constructor with an additional {@code cause} argument. 
     * 
     * @param cause     a {@code Throwable} giving the cause of the exception.
     */
    public MultipleValuesNotAllowedException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Constructor with additional {@code message} and {@code cause} arguments. 
     * 
     * @param message   a {@code String} giving details about the exception.
     * @param cause     a {@code Throwable} giving the cause of the exception.
     */
    public MultipleValuesNotAllowedException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
