package org.bgee.controller.exception;

/**
 * This <code>Exception</code> is thrown when more than one value is provided
 * to a {URLParameters} that does not allow multiple values.
 * 
 * @author 	Mathieu Seppey
 * @version Bgee 13, Jul 2014
 * @see 	org.bgee.controller.RequestParameters
 * @since 	Bgee 13
 */
public class MultipleValuesNotAllowedException extends Exception
{

	private static final long serialVersionUID = -7861781334770127365L;

	/**
	 * Default constructor
	 */
	public MultipleValuesNotAllowedException()
	{
		super();
	}
	
	/**
	 * Constructor with an additional <code>message</code> argument. 
	 * This message MUST be really basic and understandable, 
	 * as it will be displayed to the user. 
	 * 
	 * The full error message will be generated by the <code>FrontController</code>. 
	 * Only the <code>FrontController</code> should set a real error message 
	 * for this exception.
	 * 
	 * @param message 		a <code>String</code> giving details about the exception, 
	 * 						BUT despite usually, it MUST be really basic and 
	 * 						understandable, as it will be displayed to the user. 
	 */
	public MultipleValuesNotAllowedException(String message)
	{		
		super("You tried to set several values for the parameter "
				+ message + " that does not accept multiple values.");
	}
	
	/**
	 * Constructor with an additional <code>cause</code> argument. 
	 * 
	 * @param cause 		a <code>Throwable</code> giving the cause of the exception.
	 */
	public MultipleValuesNotAllowedException(Throwable cause)
	{
		super(cause);
	}
	
	/**
	 * Constructor with additional <code>message</code> and <code>cause</code> arguments. 
	 * 
	 * @param message 		a <code>String</code> giving details about the exception.
	 * @param cause 		a <code>Throwable</code> giving the cause of the exception.
	 */
	public MultipleValuesNotAllowedException(String message, Throwable cause)
	{
		super(message, cause);
	}
}
