package org.bgee.controller.exception;

/**
 * This <code>Exception</code> is thrown when a controller could not find 
 * any action corresponding to the query of the user ("404 not found"). 
 * 
 * @author 	Frederic Bastian
 * @version Bgee 12, August 2012
 * @see 	controller.CommandParent#processRequest()
 * @since 	Bgee 12
 */
public class PageNotFoundException extends Exception
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1687241145584707290L;
	
	/**
	 * Default constructor
	 */
	public PageNotFoundException()
	{
		super();
	}
	
	/**
	 * Constructor with an additional <code>message</code> argument. 
	 * This message MUST be really basic and understandable, 
	 * as it will be displayed to the user. 
	 * 
	 * The full error message will be generated by the <code>FrontController</code>. 
	 * Only the <code>FrontController</code> should set a real error message for this exception.
	 * 
	 * @param message 		a <code>String</code> giving details about the exception, 
	 * 						BUT despite usually, it MUST be really basic and understandable, 
	 * 						as it will be displayed to the user. 
	 * @see controller.FrontController#pageNotFound(PageNotFoundException, String, String)
	 */
	public PageNotFoundException(String message)
	{
		super(message);
	}
	
	/**
	 * Constructor with an additional <code>cause</code> argument. 
	 * 
	 * @param cause 		a <code>Throwable</code> giving the cause of the exception.
	 */
	public PageNotFoundException(Throwable cause)
	{
		super(cause);
	}
	
	/**
	 * Constructor with additional <code>message</code> and <code>cause</code> arguments. 
	 * 
	 * @param message 		a <code>String</code> giving details about the exception.
	 * @param cause 		a <code>Throwable</code> giving the cause of the exception.
	 */
	public PageNotFoundException(String message, Throwable cause)
	{
		super(message, cause);
	}
}
