package org.bgee.model.dao.api.expressiondata;

/**
 * This class allows to provide the parameters when using a {@link CallDAO}, 
 * to filter the {@link CallTO}s retrieved.
 * 
 * @author Frederic Bastian
 * @version Bgee 13
 * @since Bgee 13
 */
public abstract class CallQueryParams {
    /**
     * A {@code boolean} defining whether, when there are conditions on the data types
     * that should have contributed to the generation of the calls to be retrieved, 
     * the calls retrieved should satisfy all of these conditions, or at least one  
     * of these conditions. If {@code false}, they would satisfy at least one of them.
     * This is the recommended value.
     * <p>
     * For instance, if the minimum requested contributions to the calls to be 
     * retrieved, of Affymetrix and RNA-Seq data, are {@code LOWQUALITY}: 
     * if {@code allDataTypes} is {@code false}, then expression data will be retrieved 
     * from calls generated by Affymetrix or Rna-Seq data indifferently; if {@code true}, 
     * data will be retrieved from calls generated by <strong>both</code> Affymetrix 
     * and RNA-Seq data.
     */
    private boolean allDataTypes;
    
    /**
     * Default constructor.
     */
    protected CallQueryParams() {
        this.setAllDataTypes(false);
    }

    /**
     * Returns the {@code boolean} defining whether, when there are conditions on 
     * the data types that should have contributed to the generation of the calls 
     * to be retrieved, the calls retrieved should satisfy all of these conditions, 
     * or at least one  of these conditions. If {@code false}, they would satisfy 
     * at least one of them. This is the recommended value.
     * <p>
     * For instance, if the minimum requested contributions to the calls to be 
     * retrieved, of Affymetrix and RNA-Seq data, are {@code LOWQUALITY}: 
     * if {@code allDataTypes} is {@code false}, then expression data will be retrieved 
     * from calls generated by Affymetrix or Rna-Seq data indifferently; if {@code true}, 
     * data will be retrieved from calls generated by <strong>both</code> Affymetrix 
     * and RNA-Seq data.
     * 
     * @return  if {@code true}, the calls retrieved will satisfy all conditions 
     *          on data types. If {@code false}, they will satisfy at least one of them.
     */
    public boolean isAllDataTypes() {
        return allDataTypes;
    }
    /**
     * Sets the {@code boolean} defining whether, when there are conditions on 
     * the data types that should have contributed to the generation of the calls 
     * to be retrieved, the calls retrieved should satisfy all of these conditions, 
     * or at least one  of these conditions. If {@code false}, they would satisfy 
     * at least one of them. This is the recommended value.
     * <p>
     * For instance, if the minimum requested contributions to the calls to be 
     * retrieved, of Affymetrix and RNA-Seq data, are {@code LOWQUALITY}: 
     * if {@code allDataTypes} is {@code false}, then expression data will be retrieved 
     * from calls generated by Affymetrix or Rna-Seq data indifferently; if {@code true}, 
     * data will be retrieved from calls generated by <strong>both</code> Affymetrix 
     * and RNA-Seq data.
     * 
     * @param allDataTypes  if {@code true}, the calls retrieved will satisfy 
     *                      all conditions on data types. If {@code false}, they 
     *                      will satisfy at least one of them. {@code false} is 
     *                      the recommended value.
     */
    public void setAllDataTypes(boolean allDataTypes) {
        this.allDataTypes = allDataTypes;
    }
}
