package org.bgee.model.expressiondata.rawdata;

import org.bgee.model.Entity;
import org.bgee.model.expressiondata.DataParameters.CallType;
import org.bgee.model.expressiondata.DataParameters.DataQuality;

/**
 * Represents a source of gene expression data calls, for instance, 
 * an Affymetrix probeset, an EST, a value of RPKM for a gene in a RNA-Seq library.
 * <p>
 * {@code CallSource}s are always produced by {@link SampleAssay}s. 
 * The precise type of the {@code ExperimentObject} is provided by the {@code T} 
 * generic parameter.
 * 
 * @author Frederic Bastian
 * @version Bgee 13
 * @since Bgee 13
 *
 * @param <T>	The precise type of {@code ExperimentObject} that produced this 
 * 				{@code CallSource}
 */
public abstract class CallSource<T extends SampleAssay> extends Entity {
	
	/**
	 * A {@code String} corresponding to the ID 
	 * of the {@link SampleAssay} that produced this {@code CallSource}. 
	 * It can be used to load the {@link #sampleAssay} attribute after obtaining 
	 * this {@code CallSource}. 
	 * @see #sampleAssay
	 */
    private String sampleAssayId;
    /**
     * The {@link SampleAssay} that produced this {@code CallSource}.
     * @see #sampleAssayId
     */
    private T sampleAssay;
    /**
     * An {@code Expression} {@code CallType} generated by this 
     * {@code CallSource}. The related quality is stored in {@link #callQuality}.
     * @see #callQuality
     */
    private CallType.Expression callGenerated;
    /**
     * A {@code DataQuality} representing the confidence in the call generated 
     * by this {@code CallSource} (see {@link #callGenerated}).
     * @see #callGenerated
     */
    private DataQuality callQuality;
	
	/**
     * Constructor providing the {@code id} of this {@code CallSource}. 
     * This {@code id} cannot be {@code null}, or empty (""), 
     * or whitespace only, otherwise an {@code IllegalArgumentException} 
     * will be thrown. The ID will also be immutable, see {@link #getId()}.
     * 
     * @param id	A {@code String} representing the ID of this object.
     * @throws IllegalArgumentException 	if {@code id} is {@code null},  
     * 										empty, or whitespace only. 
     */
	public CallSource(String id) throws IllegalArgumentException {
		super(id);
	}
	
	/**
	 * @return 	The {@code Expression} {@code CallType} generated by this 
     * 			{@code CallSource}. The related quality is provided by 
     * 			{@link #getCallQuality()}.
     * @see #getCallQuality()
	 */
	public CallType.Expression getCallGenerated() {
		return this.callGenerated;
	}
	/**
	 * @param callGenerated 	The {@code Expression} {@code CallType} 
	 * 							generated by this {@code CallSource}. 
	 * 							The related quality is set by using
     * 							{@link #setCallQuality(DataQuality)}.
     * @see #setCallQuality(DataQuality)
	 */
	public void setCallGenerated(CallType.Expression callGenerated) {
		this.callGenerated = callGenerated;
	}

	/**
	 * @return 	the {@code DataQuality} representing the confidence in the call 
	 * 			generated by this {@code CallSource} (the related call can be 
	 * 			obtained by a call to {@link #getCallGenerated()}).
     * @see #getCallGenerated()
	 */
	public DataQuality getCallQuality() {
		return this.callQuality;
	}

	/**
	 * @param callQuality 	the {@code DataQuality} representing the confidence 
	 * 						in the call generated by this {@code CallSource} 
	 * 						(the related call can be set by calling {@link 
	 * 						#setCallGenerated(CallType.Expression)}).
     * @see #setCallGenerated(CallType.Expression)
	 */
	public void setCallQuality(DataQuality callQuality) {
		this.callQuality = callQuality;
	}

	/**
	 * Load the {@link SampleAssay} that produced this {@code CallSource}, 
	 * by obtaining it from a {@code DAO}, only if not already loaded 
	 * ({@link #getSampleAssay()} returning {@code null}).
	 * 
	 * @see #getSampleAssay()
	 * @see #getSampleAssayId()
	 */
	public abstract void loadSampleAssay();
	
	/**
	 * Get the ID of the {@link SampleAssay} that produced this {@code CallSource}.
	 * 
	 * @return 	a {@code String} corresponding to the {@code SampleAssay} ID.
	 * @see #getSampleAssay()
	 */
	public String getSampleAssayId() {
		if (this.getSampleAssay() != null) {
			return this.getSampleAssay().getId();
		} 
		return this.sampleAssayId;
	}

	/**
	 * Set the ID of the {@link SampleAssay} that produced this {@code CallSource}. 
	 * This is useful when retrieving this {@code CallSource} 
	 * from a {@code DAO}, before loading the actual {@code SampleAssay}.
	 * 
	 * @param 	A {@code String} that is the ID of the {@code SampleAssay} 
	 * 			that produced this {@code CallSource}
	 */
	public void setSampleAssayId(String sampleAssayId) {
		this.sampleAssayId = sampleAssayId;
	}

	/**
	 * Get the {@link SampleAssay} that produced this {@code CallSource}. 
	 * Should return {@code null} if it has not yet been loaded 
	 * (using {@link #loadSampleAssay()}), or set (using 
	 * {@link setSampleAssay(SampleAssay)})
	 * 
	 * @return	the {@code SampleAssay} that produced this {@code CallSource}.
	 */
	public T getSampleAssay() {
		return this.sampleAssay;
	}

	/**
	 * Set the {@link SampleAssay} that produced this {@code CallSource}. 
	 * @param 	sampleAssay The {@code SampleAssay} to set.
	 */
	public void setSampleAssay(T sampleAssay) {
		this.sampleAssay = sampleAssay;
	}
}
