package org.bgee.controller;


import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bgee.controller.exception.PageNotFoundException;
import org.bgee.model.BgeeUtils;
import org.bgee.model.Service;
import org.bgee.model.ServiceFactory;
import org.bgee.model.expressiondata.Call;
import org.bgee.model.expressiondata.Call.ExpressionCall;
import org.bgee.model.expressiondata.Call.ExpressionCall.ClusteringMethod;
import org.bgee.model.expressiondata.CallData.ExpressionCallData;
import org.bgee.model.expressiondata.CallFilter.ExpressionCallFilter;
import org.bgee.model.expressiondata.CallService;
import org.bgee.model.expressiondata.Condition;
import org.bgee.model.expressiondata.ConditionUtils;
import org.bgee.model.expressiondata.baseelements.CallType.Expression;
import org.bgee.model.expressiondata.baseelements.DataPropagation;
import org.bgee.model.gene.Gene;
import org.bgee.model.gene.GeneFilter;
import org.bgee.view.GeneDisplay;
import org.bgee.view.ViewFactory;

/**
 * Controller handling requests related to gene pages. 
 * 
 * @author Philippe Moret
 * @author Frederic Bastian
 * @version Bgee 13, Jan. 2016
 * @since   Bgee 13, Nov. 2015
 */
public class CommandGene extends CommandParent {

    private final static Logger log = LogManager.getLogger(CommandGene.class.getName());
    
    /**
     * Contains all information necessary to produce a view related to a {@code Gene}.
     * 
     * @author Frederic Bastian
     * @version Bgee 13, Jan. 2016
     * @since   Bgee 13, Jan. 2016
     */
    public static class GeneResponse {
        private final Gene gene;
        private final List<ExpressionCall> exprCalls;
        private final Set<ExpressionCall> redundantExprCalls;
        private final Map<ExpressionCall, Integer> clusteringBestEachAnatEntity;
        private final Map<ExpressionCall, Integer> clusteringWithinAnatEntity;
        private final ConditionUtils conditionUtils;
        
        /**
         * @param gene                          See {@link #getGene()}.
         * @param exprCalls                     See {@link #getExprCalls()}.
         * @param redundantExprCalls            See {@link #getRedundantExprCalls()}.
         * @param clusteringBestEachAnatEntity  See {@link #getClusteringBestEachAnatEntity()}.
         * @param clusteringWithinAnatEntity    See {@link #getClusteringWithinAnatEntity()}.
         * @param conditionUtils                See {@link #getConditionUtils()}.
         */
        public GeneResponse(Gene gene, List<ExpressionCall> exprCalls, 
                Set<ExpressionCall> redundantExprCalls, 
                Map<ExpressionCall, Integer> clusteringBestEachAnatEntity, 
                Map<ExpressionCall, Integer> clusteringWithinAnatEntity, 
                ConditionUtils conditionUtils) {
            this.gene = gene;
            this.exprCalls = BgeeUtils.toList(exprCalls);
            this.redundantExprCalls = BgeeUtils.toSet(redundantExprCalls);
            this.clusteringBestEachAnatEntity = clusteringBestEachAnatEntity;
            this.clusteringWithinAnatEntity = clusteringWithinAnatEntity;
            this.conditionUtils = conditionUtils;
        }

        /**
         * @return  The {@code Gene} which information are requested for. 
         */
        public Gene getGene() {
            return gene;
        }
        /**
         * @return  A {@code List} of {@code ExpressionCall}s, ranked by the normalized global rank 
         *          of the gene in the related {@code Condition}s.
         */
        public List<ExpressionCall> getExprCalls() {
            return exprCalls;
        }
        /**
         * @return  A {@code Set} of {@code ExpressionCall}s for which there exists a more precise call 
         *          (i.e., with a more precise {@code Condition}), at a better rank (i.e., 
         *          with a lower index in the {@code List} returned by {@link #getExprCalls()})
         */
        public Set<ExpressionCall> getRedundantExprCalls() {
            return redundantExprCalls;
        }
        /**
         * Returns a clustering of a set of {@code ExpressionCall}s generated by only considering  
         * the best non-redundant {@code ExpressionCall} from each anatomical entity. 
         * 
         * @return      A {@code Map} where keys are {@code ExpressionCall}s, the associated value 
         *              being the index of the group in which they are clustered, 
         *              based on their expression score. Group indexes are assigned in ascending 
         *              order of expression score, starting from 0. Only one best non-redundant 
         *              {@code ExpressionCall} per anatomical entity is considered. 
         */
        public Map<ExpressionCall, Integer> getClusteringBestEachAnatEntity() {
            return clusteringBestEachAnatEntity;
        }
        /**
         * Returns a clustering of {@code ExpressionCall}s clustered independently 
         * for each anatomical entity (so, {@code ExpressionCall}s associated to a same value 
         * in the returned {@code Map} might not be part of a same cluster). 
         * Only non-redundant {@code ExpressionCall}s were considered. 
         * 
         * @return      A {@code Map} where keys are {@code ExpressionCall}s, the associated value 
         *              being the index of the group in which they are clustered, 
         *              based on their expression score. Group indexes are assigned in ascending 
         *              order of expression score, starting from 0. Clusters are independent 
         *              per anatomical entities, considering all non-redundant 
         *              {@code ExpressionCall}s associated to an anatomical entity. 
         */
        public Map<ExpressionCall, Integer> getClusteringWithinAnatEntity() {
            return clusteringWithinAnatEntity;
        }
        /**
         * @return  A {@code ConditionUtils} loaded from all {@code Condition}s 
         *          retrieved from the {@code ExpressionCall}s in the {@code List} returned by 
         *          {@link #getExprCalls()}.
         */
        public ConditionUtils getConditionUtils() {
            return conditionUtils;
        }
    }

    /**
     * Constructor
     * 
     * @param response          A {@code HttpServletResponse} that will be used to display the 
     *                          page to the client
     * @param requestParameters The {@code RequestParameters} that handles the parameters of the 
     *                          current request.
     * @param prop              A {@code BgeeProperties} instance that contains the properties
     *                          to use.
     * @param viewFactory       A {@code ViewFactory} that provides the display type to be used.
     * @param serviceFactory    A {@code ServiceFactory} that provides bgee services.
     */
	public CommandGene(HttpServletResponse response, RequestParameters requestParameters, BgeeProperties prop,
	        ViewFactory viewFactory, ServiceFactory serviceFactory) {
		super(response, requestParameters, prop, viewFactory, serviceFactory);
	}

	@Override
	public void processRequest() throws Exception {
		log.entry();
		GeneDisplay display = viewFactory.getGeneDisplay();
		String geneId = requestParameters.getGeneId();
		if (geneId == null) {
			display.displayGeneHomePage();
		} else {
			display.displayGene(this.buildGeneResponse(geneId));
		}
		log.exit();
	}

	private GeneResponse buildGeneResponse(String geneId) throws PageNotFoundException {
	    log.entry(geneId);

        //*********************
        // Retrieve Gene
        //*********************
	    Gene gene = this.getGene(geneId);
	    
        //*********************
        // Expression calls, ConditionUtils, and redundant calls
        //*********************
	    List<ExpressionCall> exprCalls = this.getExpressions(gene);
	    if (exprCalls.isEmpty()) {
	        log.debug("No calls for gene {}", geneId);
	         return log.exit(new GeneResponse(gene, exprCalls, new HashSet<ExpressionCall>(), 
	                 null, null, null));
	    }
        //we need to make sure that the ExpressionCalls are ordered exactly as used for the clustering, 
        //otherwise the display will be buggy, notably for calls with equal scores. 
        //So, even if they were ordered through the query to the data source, we reorder them 
        //using the ExpressionCall Comparator.
        Collections.sort(exprCalls, ExpressionCall.RANK_COMPARATOR);
        
	    ConditionUtils conditionUtils = new ConditionUtils(gene.getSpeciesId(), 
	            exprCalls.stream().map(ExpressionCall::getCondition).collect(Collectors.toSet()), 
	            serviceFactory);
        log.debug("Expressions: {} {}", exprCalls.size(), exprCalls);
        
        final Set<ExpressionCall> redundantCalls = getRedundantCalls(exprCalls, conditionUtils);
        
        //*********************
        // Clusterings
        //*********************
        //first, group calls by anat. entity. 
        Map<String, List<ExpressionCall>> callsByAnatEntityId = exprCalls.stream()
                .collect(Collectors.groupingBy(ec -> ec.getCondition().getAnatEntityId()));
        
        //define clustering method
        //ClusteringMethod.CANBERRA_DIST_TO_MAX, 0.19
        //ClusteringMethod.FIXED_CANBERRA_DIST_TO_MAX, 0.19
        //ClusteringMethod.CANBERRA_DIST_TO_MIN, 0.2
        //ClusteringMethod.CANBERRA_DIST_TO_MEAN, 0.18
        
        //default clustering method and threshold if nothing specified in properties
        Function<Collection<ExpressionCall>, Map<ExpressionCall, Integer>> clusteringFunction = 
                c -> ExpressionCall.generateMeanRankScoreClustering(c);
        //if clustering method specified in properties
        if (this.prop.getGeneScoreClusteringMethod() != null) {
            //Distance threshold
            if (this.prop.getGeneScoreClusteringThreshold() == null || 
                    //we don't want negative nor near-zero values
                    this.prop.getGeneScoreClusteringThreshold() < 0.000001) {
                throw log.throwing(new IllegalStateException("A clustering method was specified, "
                        + "but no distance threshold or incorrect threshold value assigned."));
            }
            
            try {
                //find clustering method
                final ClusteringMethod method = ClusteringMethod.valueOf(
                        this.prop.getGeneScoreClusteringMethod().trim());
                
                //define clustering function
                clusteringFunction = c -> ExpressionCall.generateMeanRankScoreClustering(c, method, 
                        this.prop.getGeneScoreClusteringThreshold());
                log.debug("Using clustering method {} with distance threshold {}", method, 
                        this.prop.getGeneScoreClusteringThreshold());
                
            } catch (IllegalArgumentException e) {
                throw log.throwing(new IllegalStateException("No custering method corresponding to "
                        + this.prop.getGeneScoreClusteringMethod().trim()));
            }
        } else {
            log.debug("Using default clustering method");
        }
        
//        //store one best call from each anat. entity
//        //(we don't do it immediately using Streams as we are going to iterate 
//        //callsByAnatEntityId anyway)
//        NOTE: disabled as long as we don't use redundant calls at all. 
//        Set<ExpressionCall> bestEachAnatEntity = new HashSet<>();

        //store one best call from each anat. entity, excluding redundant calls
        Set<ExpressionCall> bestEachAnatEntityNoRedundant = new HashSet<>();
        
//        //store a clustering, independent for each anatomical entity, of all the ExpressionCalls 
//        //of an anatomical entity
//        NOTE: disabled as long as we don't use redundant calls at all. 
//        GeneResponse should be updated to store this clustering. 
//        Map<ExpressionCall, Integer> clusteringWithinAnatEntity = new HashMap<>();
        
        //store a clustering, independent for each anatomical entity, of the ExpressionCalls 
        //of an anatomical entity, excluding redundant calls
        Map<ExpressionCall, Integer> clusteringWithinAnatEntityNoRedundant = new HashMap<>();
        
        for (List<ExpressionCall> callGroup: callsByAnatEntityId.values()) {
//            NOTE: disabled as long as we don't use redundant calls at all. 
//            bestEachAnatEntity.add(callGroup.get(0));
//            clusteringWithinAnatEntity.putAll(clusteringFunction.apply(callGroup));
            
            List<ExpressionCall> filteredList = callGroup.stream()
                    .filter(call -> !redundantCalls.contains(call)).collect(Collectors.toList());
            if (!filteredList.isEmpty()) {
                bestEachAnatEntityNoRedundant.add(filteredList.get(0));
                clusteringWithinAnatEntityNoRedundant.putAll(clusteringFunction.apply(filteredList));
            }
        }
//        //store a clustering of the best ExpressionCall from each anatomical entity
//        NOTE: disabled as long as we don't use redundant calls at all. 
//        GeneResponse should be updated to store this clustering. 
//        Map<ExpressionCall, Integer> clusteringBestEachAnatEntity = 
//                clusteringFunction.apply(bestEachAnatEntity);
        
        //store a clustering of the best ExpressionCall from each anatomical entity, 
        //excluding redundant calls. 
        log.trace("Best non-redundant call per anat. entity: {}", bestEachAnatEntityNoRedundant);
        Map<ExpressionCall, Integer> clusteringBestEachAnatEntityNoRedundant = 
                clusteringFunction.apply(bestEachAnatEntityNoRedundant);
        
        //*********************
        // Build GeneResponse
        //*********************
	    return log.exit(new GeneResponse(gene, exprCalls, redundantCalls, 
	            clusteringBestEachAnatEntityNoRedundant, clusteringWithinAnatEntityNoRedundant, 
	            conditionUtils));
	}
	
	/**
	 * Gets the {@code Gene} instance from its id. 
	 * 
	 * @param geneId A {@code String} containing the gene id.
	 * @return       The {@code Gene} instance.
	 * @throws PageNotFoundException   If no {@code Gene} could be found corresponding to {@code geneId}.
	 */
	private Gene getGene(String geneId) throws PageNotFoundException {
	    log.entry(geneId);
		Gene gene = serviceFactory.getGeneService().loadGeneById(geneId);
		if (gene == null) {
		    throw log.throwing(new PageNotFoundException("No gene corresponding to " + geneId));
		}
		return log.exit(gene);
	}
	
	/**
	 * Retrieves the sorted list of {@code ExpressionCall} associated to this gene, 
	 * ordered by biological relevance.
	 * 
	 * @param gene The {@code Gene}
	 * @return     The {@code List} of {@code ExpressionCall} associated to this gene, ordered by relevance.
	 */
	private List<ExpressionCall> getExpressions(Gene gene) {
	    log.entry(gene);
	    
		LinkedHashMap<CallService.OrderingAttribute, Service.Direction> serviceOrdering = 
	                new LinkedHashMap<>();
	    serviceOrdering.put(CallService.OrderingAttribute.GLOBAL_RANK, Service.Direction.ASC);
	    //important for consistent ranking of equal scores
        serviceOrdering.put(CallService.OrderingAttribute.ANAT_ENTITY_ID, Service.Direction.ASC);
        serviceOrdering.put(CallService.OrderingAttribute.DEV_STAGE_ID, Service.Direction.ASC);
	        
		CallService service = serviceFactory.getCallService();
		return log.exit(service.loadExpressionCalls(
		        gene.getSpeciesId(), 
                new ExpressionCallFilter(new GeneFilter(gene.getId()), null, new DataPropagation(), 
                        Arrays.asList(new ExpressionCallData(Expression.EXPRESSED))), 
                EnumSet.of(CallService.Attribute.GENE_ID, CallService.Attribute.ANAT_ENTITY_ID, 
                        CallService.Attribute.DEV_STAGE_ID, CallService.Attribute.CALL_DATA, 
                        CallService.Attribute.GLOBAL_DATA_QUALITY, CallService.Attribute.GLOBAL_RANK), 
                serviceOrdering)
            .collect(Collectors.toList()));
	}

    /**
     * Identifies redundant {@code Calls} from the provided {@code List}. This method returns
     * {@code Call}s for which there exists a more precise call (i.e., with a more 
     * precise condition), at a better rank (i.e., with a lower index in the provided list). 
     * 
     * @param calls            The original ranked {@code List} of {@code Call}s.
     * @param conditionUtils   A {@code ConditionUtils}, containing all the {@code Condition}s 
     *                         related to {@code calls}.
     * @return                 A {@code Set} containing the {@code Call}s that are redundant.
     * @param <T>              The type of {@code Call} to be filtered.
     */
    private static <T extends Call<?, ?>> Set<T> getRedundantCalls(List<T> calls, ConditionUtils conditionUtils) {
        log.entry(calls, conditionUtils);

        long startFilteringTimeInMs = System.currentTimeMillis();
        
        Set<T> redundantCalls = new HashSet<>();
        Set<Condition> validatedConditions = new HashSet<>();
        for (T call: calls) {
            //Check whether this call is less precise than another call with a better rank. 
            Condition cond = call.getCondition();
            if (Collections.disjoint(validatedConditions, conditionUtils.getDescendantConditions(cond))) {
                log.trace("Valid call identified with condition: {}", cond);
                validatedConditions.add(cond);
            } else {
                log.trace("Redundant call identified with condition: {}", cond);
                redundantCalls.add(call);
            }
        }
        log.debug("Redundant calls filtered in {} ms", System.currentTimeMillis() - startFilteringTimeInMs);
        
        return log.exit(redundantCalls);
    }
}
