package org.bgee.model.expressiondata.querytools.filters;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bgee.model.expressiondata.DataParameters.CallType;
import org.bgee.model.expressiondata.DataParameters.DiffExpressionFactor;

/**
 * A <code>BasicCallFilter</code> for differential expression calls.
 * To instantiate a <code>DiffExpressionCallFilter</code>, a differential expression 
 * <code>CallType</code> and a <code>DiffExpressionFactor</code> must be provided. 
 * The list of differential expression <code>CallType</code>s (for instance, 
 * <code>OVEREXPRESSION</code>) can be obtained by calling {@link 
 * org.bgee.model.expressiondata.DataParameters.CallType#getDiffExpressionCalls() 
 * CallType.getDiffExpressionCalls()}. The <code>DiffExpressionFactor</code> allows 
 * to specify what is the experimental factor the expression comparisons should be based on, 
 * to generate the differential expression calls. For instance, <code>ANATOMY</code> 
 * indicates that the calls are generated by comparing expression in different 
 * organs at a same (broad) developmental stage. 
 * 
 * @author Frederic Bastian
 * @version Bgee 13
 * @since Bgee 13
 */
public class DiffExpressionCallFilter extends BasicCallFilter {
	/**
	 * <code>Logger</code> of the class. 
	 */
	private final static Logger log = LogManager.getLogger(DiffExpressionCallFilter.class.getName());

    /**
     * An <code>int</code> defining the requested minimum number of conditions 
     * compared when generating the differential expression data. For instance, 
     * to use analyses having compared at least 3 organs. The minimum number 
     * of conditions specified by the Bgee pipeline to proceed to a differential 
     * expression analysis is applicable in any case.  
     */
    private int conditionCount;
    /**
     * A <code>DiffExpressionFactor</code> defining which type of differential analysis  
     * should be used to retrieve differential expression calls. 
     */
    private final DiffExpressionFactor factor;
    
	/**
     * Instantiate a <code>DiffExpressionCallFilter</code> for the given 
     * <code>callType</code> and <code>factor</code>, with no minimum number 
     * of conditions compared requested (besides the default threshold of the Bgee pipeline).
     * <p>
     * if <code>callType</code> is not applicable to differential expression (see 
     * {@link org.bgee.model.expressiondata.DataParameters.CallType#isADiffExpressionCall()}), 
     * an <code>IllegalArgumentException</code> is thrown. 
     * 
     * @param callType	A <code>CallType</code> defining the type of differential 
     * 					expression calls to use. 
     * @param factor	A <code>DiffExpressionFactor</code> specifying 
     * 					the experimental factor of the differential expression 
     * 					analyses that should be used.
     * @throws IllegalArgumentException 	if <code>callType</code> is not a differential 
     * 										expression call type. 
     */
    public DiffExpressionCallFilter(CallType callType, DiffExpressionFactor factor) 
        throws IllegalArgumentException
    {
    	super(callType);
    	log.entry(callType, factor);
    	if (!callType.isADiffExpressionCall()) {
    		throw log.throwing(new IllegalArgumentException(callType + 
    				" is not a differential expression call. A differential " +
    				"expression call type must be specified to instantiate " +
    				"a DiffExpressionCallFilter"));
    	}
    	this.factor = factor;
    	this.setConditionCount(0);
    	log.exit();
    }

	/**
	 * Return the experimental factor that the differential expression analyses used 
	 * should be based on. 
	 * @return 	a <code>DiffExpressionFactor</code> defining which type of 
	 * 			differential analysis  should be used to retrieve differential 
	 * 			expression calls. 
	 */
	public DiffExpressionFactor getFactor() {
		return this.factor;
	}
    
	/**
	 * @return 	An <code>int</code> defining the requested minimum number of conditions 
     * 			compared when generating the differential expression data. For instance, 
     * 			one organ compared at three developmental stages would represent 
     * 			three conditions.
	 */
	public int getConditionCount() {
		return this.conditionCount;
	}
	/**
	 * @param conditionCount 	An <code>int</code> defining the requested minimum number 
	 * 							of conditions compared when generating the differential 
	 * 							expression data. For instance, one organ compared 
	 * 							at three developmental stages would represent three conditions.
	 */
	public void setConditionCount(int conditionCount) {
		this.conditionCount = conditionCount;
	}
}
