#!/usr/bin/env perl

# Perl embedded modules
use strict;
use warnings;
use diagnostics;

use Mail::Send;


my $user_email = 'bgee_team@unil.ch'; # Comma-separated if several ones
my $log        = '/tmp/bgee-ftp_failure';

if ( system("wget -S -O /dev/null 'https://bgee.org/ftp/' 2> $log")!=0 ){
    my $host = $ENV{'HOSTNAME'} || `hostname`; chomp $host;
    my $msg = new Mail::Send Subject=>"[BGEE-FTP: service failure] from $host", To=>"$user_email";
    $msg->add('From', 'Bgee@sib.swiss');
    $msg->add('X-Mailer', "Mail::Send ($Mail::Send::VERSION) Perl module");
    my $fh  = $msg->open;
    print {$fh} `cat "$log"`;
    $fh->close; # complete the message and send it
}

unlink "$log";

exit 0;

